### ISSUE TITLE
Init Jekyll site

### ISSUE THREAD

**Issue by danielfeelfine** [wejs/website#1]
[Jekyll](http://jekyllrb.com/) is than better of for create static pages. And static page for WeJS can contain all about docs, how to run (and plug/install smaller parts) and the online example (which is now in actual website). Like [Sailsjs.org](http://sailsjs.org/), and this don't show the online example, but a ```getting started``` section, ```documentation``` etc.

**Comment by albertosouza** [comment]
uneed
